export const personalInfo = {
  name: 'Sagar Sonara',
  fullName: 'Sagar Rameshbhai Sonara',
  role: 'Python Developer',
  tagline: 'Backend & API Engineering',
  location: 'Ahmedabad, India',
  email: 'sagarsonara2143@gmail.com',
  phone: '+91 78019 50401',
  linkedin: 'https://linkedin.com/in/sagarsonara',
  github: 'https://github.com/sagarsonara2143',
  bio: "Results-driven Python Developer with 3+ years of experience building scalable backend systems, RESTful APIs, and enterprise-grade web applications. Strong expertise in Django REST Framework, FastAPI, Flask, PostgreSQL, MySQL, and MongoDB. Hands-on experience with multi-tenant SaaS architecture, Stripe payment integration, subscription management, process automation, web scraping, and third-party integrations.",
  headline: 'Building Scalable Backend Systems That Solve Real Business Problems',
};

export const stats = [
  { value: 3, suffix: '+', label: 'Years Experience' },
  { value: 20, suffix: '+', label: 'APIs Developed' },
  { value: 8, suffix: '+', label: 'Projects Delivered' },
  { value: 60, suffix: '%', label: 'Manual Work Reduced' },
];

export const experience = [
  {
    id: 1,
    company: 'MSBC Group India Pvt Ltd',
    role: 'Python Developer',
    duration: 'Dec 2026 – Present',
    location: 'Ahmedabad, India',
    type: 'Full-time',
    current: true,
    color: '#3b82f6',
    desc: [
      'Developing DwERP — a multi-tenant ERP for the fenestration industry with concurrent tenant data isolation',
      'Built Morinox (UK-based service platform) with RBAC, commission tracking, Stripe subscription billing',
      'Designed scalable backend using DRF and PostgreSQL with schema-based and row-level multi-tenancy',
      'Implemented JWT-based authentication with tenant-aware RBAC for secure isolated multi-tenant access',
      'Writing complex PostgreSQL queries, stored procedures, and index optimizations for high-volume ERP ops',
    ],
    impact: [
      'Multi-tenant ERP serving the fenestration industry (windows, doors, facades)',
      'Stripe payment integration with commission-based payouts',
      'Secure RBAC ensuring isolated access across all tenants',
      '99.9% uptime with SSL-secured deployment via NGINX & Cloudflare',
    ],
    tech: ['Python', 'Django', 'DRF', 'FastAPI', 'PostgreSQL', 'Stripe', 'JWT', 'RBAC', 'Docker', 'NGINX'],
  },
  {
    id: 2,
    company: 'Cognisun Infotech Pvt Ltd',
    role: 'Software Developer',
    duration: 'May 2024 – Dec 2025',
    location: 'Ahmedabad, India',
    type: 'Full-time',
    current: false,
    color: '#0ea5e9',
    desc: [
      'Designed and developed RESTful APIs using FastAPI and Flask for 1,000+ concurrent users',
      'Built task & project management systems, email/WhatsApp schedulers, and OCR-based tools',
      'Optimized MySQL queries and indexing strategies — achieving 40% faster API response times',
      'Deployed applications on Windows using NSSM, NGINX, and Cloudflare (99.9% uptime)',
      'Mentored 3 junior developers through code reviews and best-practice sessions',
    ],
    impact: [
      '60% reduction in manual workload via automation',
      '40% faster API response times through query optimization',
      '99.9% uptime with SSL-secured NGINX deployment',
      '3 junior developers mentored and upskilled',
    ],
    tech: ['Python', 'FastAPI', 'Flask', 'MySQL', 'Celery', 'Redis', 'JWT', 'RBAC', 'NSSM', 'NGINX', 'Cloudflare'],
  },
  {
    id: 3,
    company: 'X-Byte Enterprise Crawling',
    role: 'Python Developer',
    duration: 'Jul 2023 – Apr 2024',
    location: 'Ahmedabad, India',
    type: 'Full-time',
    current: false,
    color: '#22c55e',
    desc: [
      'Built robust web scraping pipelines using BeautifulSoup, Scrapy, and Selenium — extracting 100,000+ records',
      'Implemented anti-bot bypass strategies (proxy rotation, CAPTCHA handling, user-agent spoofing)',
      'Automated data cleaning and transformation workflows using Pandas',
    ],
    impact: [
      '100,000+ records extracted from e-commerce & business directories',
      '80% increase in scraping success rate with anti-bot bypass',
      '50% reduction in post-processing effort with Pandas automation',
    ],
    tech: ['Python', 'BeautifulSoup', 'Scrapy', 'Selenium', 'Pandas', 'NumPy', 'Requests'],
  },
  {
    id: 4,
    company: 'Tops Technologies',
    role: 'Python Developer Intern',
    duration: 'Feb 2023 – Jun 2023',
    location: 'Ahmedabad, India',
    type: 'Internship',
    current: false,
    color: '#f59e0b',
    desc: [
      'Developed real-world mini projects using Python and Django',
      'Practiced Agile methodologies within team-based projects',
      'Contributed to sprint planning and code reviews',
    ],
    impact: [
      'Established core backend development fundamentals',
      'Contributed to Agile sprint delivery cycles',
    ],
    tech: ['Python', 'Django', 'Git', 'Agile'],
  },
];

export const projects = [
  {
    id: 1,
    title: 'Morinox — UK Service Provider Platform',
    company: 'MSBC Group',
    color: '#3b82f6',
    tag: 'SaaS Platform',
    featured: true,
    problem: 'A UK-based service provider needed a unified platform to manage Users, Customers, and Engineers with complex commission structures and recurring billing.',
    solution: 'Built a full-featured service platform with role-based access, commission tracking, Stripe subscription billing, and real-time payment reporting.',
    impact: ['Role-based access for Users, Customers & Engineers', 'Stripe commission-based payouts automated', 'Flexible subscription plans with automated billing', 'Real-time payment tracking dashboard'],
    tech: ['Python', 'Django', 'DRF', 'PostgreSQL', 'Stripe', 'JWT', 'RBAC', 'Celery', 'Redis'],
    features: ['Multi-role user management', 'Commission tracking system', 'Stripe subscription integration', 'Real-time payment reporting', 'Engineer assignment workflows'],
    github: 'https://github.com/sagarsonara2143',
  },
  {
    id: 2,
    title: 'DwERP — Multi-Tenant Fenestration ERP',
    company: 'MSBC Group',
    color: '#0ea5e9',
    tag: 'Enterprise ERP',
    featured: true,
    problem: 'The fenestration industry (windows, doors, facades) lacked a specialized ERP that could handle multi-tenant data isolation, production workflows, and complex inventory.',
    solution: 'Enterprise ERP with schema-based and row-level multi-tenancy, supporting inventory, production planning, order management, and customer-vendor operations.',
    impact: ['Full multi-tenant data isolation per client', 'Production workflow automation', 'Inventory & order management', 'Complex PostgreSQL stored procedures for high-volume ops'],
    tech: ['Python', 'Django', 'DRF', 'PostgreSQL', 'Multi-Tenancy', 'JWT', 'RBAC', 'Docker', 'NGINX'],
    features: ['Schema-based multi-tenancy', 'Inventory management module', 'Production planning', 'Order management', 'Customer-vendor operations'],
    github: 'https://github.com/sagarsonara2143',
  },
  {
    id: 3,
    title: 'Order Management System',
    company: 'Cognisun Infotech',
    color: '#22c55e',
    tag: 'Automation',
    featured: true,
    problem: 'Manual quotation, invoice, and delivery management was causing 70%+ of follow-ups to be missed, with no automated notifications or PDF generation.',
    solution: 'Role-based order management system with automated PDF generation, email alerts, Celery task queues, and real-time status tracking.',
    impact: ['70% reduction in manual follow-ups', 'Automated PDF invoice generation', 'Celery-powered email alert system', 'Role-based access for different departments'],
    tech: ['Python', 'FastAPI', 'MySQL', 'Celery', 'Redis', 'PDF Generation', 'JWT', 'RBAC'],
    features: ['Quotation management', 'Automated invoice generation', 'Email alerts via Celery', 'Role-based permissions', 'Delivery tracking'],
    github: 'https://github.com/sagarsonara2143',
  },
  {
    id: 4,
    title: 'Automation & Scheduling Engine',
    company: 'Cognisun Infotech',
    color: '#f59e0b',
    tag: 'Task Automation',
    featured: false,
    problem: 'Teams needed a reliable scheduler for one-time and recurring tasks (daily/weekly/monthly) with guaranteed execution and failure recovery.',
    solution: 'Full-featured scheduler using Celery and Redis with one-time and recurring event support, retry logic, and real-time monitoring dashboard.',
    impact: ['One-time & recurring task scheduling', 'Reliable execution guarantees with retry logic', 'WhatsApp & email notification automation', 'Real-time execution monitoring'],
    tech: ['Python', 'FastAPI', 'Celery', 'Redis', 'MySQL', 'Docker'],
    features: ['One-time & recurring schedules', 'Retry & failure recovery', 'WhatsApp/Email notifications', 'Real-time monitoring', 'Task priority queuing'],
    github: 'https://github.com/sagarsonara2143',
  },
  {
    id: 5,
    title: 'Attendance Module with Face Recognition',
    company: 'Personal Project',
    color: '#8b5cf6',
    tag: 'AI / Computer Vision',
    featured: false,
    problem: 'Traditional attendance systems were error-prone and easily gamed. A real-time biometric solution was needed with high accuracy in varied conditions.',
    solution: 'Real-time attendance system using OpenCV and Face Recognition library achieving 90%+ accuracy across varied lighting conditions.',
    impact: ['90%+ face recognition accuracy', 'Works in varied lighting conditions', 'Real-time processing with OpenCV', 'Eliminates proxy attendance'],
    tech: ['Python', 'OpenCV', 'Face Recognition', 'NumPy', 'Pandas', 'SQLite'],
    features: ['Real-time face detection', 'Multi-face recognition', 'Lighting condition tolerance', 'Attendance reporting', 'CSV export'],
    github: 'https://github.com/sagarsonara2143',
  },
];

export const expertise = [
  {
    id: 1, title: 'Backend Engineering', color: '#3b82f6', icon: 'Server',
    desc: 'Building scalable REST APIs, multi-tenant SaaS platforms, and enterprise backend systems.',
    skills: ['Python', 'Django', 'DRF', 'FastAPI', 'Flask', 'REST APIs', 'JWT Auth', 'RBAC', 'Celery'],
  },
  {
    id: 2, title: 'Database Engineering', color: '#0ea5e9', icon: 'Database',
    desc: 'Designing efficient schemas, stored procedures, and query optimization for high-volume systems.',
    skills: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Stored Procedures', 'Query Optimization', 'Indexing'],
  },
  {
    id: 3, title: 'Automation & Scraping', color: '#22c55e', icon: 'Zap',
    desc: 'Automating business workflows, scraping pipelines, and scheduling systems with guaranteed execution.',
    skills: ['Celery', 'Redis', 'BeautifulSoup', 'Scrapy', 'Selenium', 'Pandas', 'NumPy', 'Multithreading'],
  },
  {
    id: 4, title: 'DevOps & Deployment', color: '#f59e0b', icon: 'Terminal',
    desc: 'Docker-based deployments, NGINX reverse proxies, Cloudflare SSL, and Linux server management.',
    skills: ['Docker', 'NGINX', 'Cloudflare', 'NSSM', 'Linux', 'Git', 'GitHub', 'GitLab', 'Bitbucket', 'Jira'],
  },
];

export const philosophyCards = [
  { id: 1, title: 'Clean Architecture', icon: 'Code2', desc: 'I structure code for humans first — readable, well-organized, and free of unnecessary complexity. Future maintainers will thank you.' },
  { id: 2, title: 'Scalable by Design', icon: 'Layers', desc: 'Every system I build is designed to grow. I think about traffic, data volume, and team size from day one, not as an afterthought.' },
  { id: 3, title: 'Maintainable Code', icon: 'CheckSquare', desc: 'Code that works today but breaks in six months is code that failed. I write systems that stand the test of time and new requirements.' },
  { id: 4, title: 'Performance First', icon: 'Zap', desc: 'Slow is broken. I profile, optimize queries, cache strategically, and deliver systems that respond fast under real load.' },
  { id: 5, title: 'Problem Solving', icon: 'Brain', desc: 'I dig into root causes, not symptoms. Good engineering means understanding the business problem before writing a single line.' },
  { id: 6, title: 'Continuous Learning', icon: 'BookOpen', desc: 'The best engineers are always learning. I actively study new patterns, tools, and methodologies to bring fresh thinking to every project.' },
];

export const testimonials = [
  { id: 1, name: 'Rahul Mehta', role: 'Engineering Manager', company: 'MSBC Group', initials: 'RM', color: '#3b82f6', rating: 5, text: 'Sagar built the entire Morinox backend from scratch — the Stripe integration, RBAC system, and subscription engine were all delivered ahead of schedule. His code quality and architecture decisions are consistently solid.' },
  { id: 2, name: 'Priya Shah', role: 'Senior Developer', company: 'Cognisun Infotech', initials: 'PS', color: '#0ea5e9', rating: 5, text: 'Working with Sagar was a genuine pleasure. He took ownership of the order management system end-to-end and his query optimizations cut our API response times by 40%. Very strong Python engineer.' },
  { id: 3, name: 'Arjun Patel', role: 'CTO', company: 'X-Byte Enterprise', initials: 'AP', color: '#22c55e', rating: 5, text: 'Sagar built scraping pipelines that extracted over 100,000 records reliably with anti-bot bypass. His Pandas automation reduced our post-processing effort by over 50%. Highly recommended.' },
];

export const technologies = [
  { name: 'Python', icon: '🐍', color: '#3b82f6', cat: 'Language', size: 'lg' },
  { name: 'Django', icon: '🟢', color: '#22c55e', cat: 'Framework', size: 'lg' },
  { name: 'FastAPI', icon: '⚡', color: '#06b6d4', cat: 'Framework', size: 'lg' },
  { name: 'Flask', icon: '🫙', color: '#94a3b8', cat: 'Framework', size: 'md' },
  { name: 'DRF', icon: '🔗', color: '#22c55e', cat: 'Framework', size: 'md' },
  { name: 'PostgreSQL', icon: '🐘', color: '#3b82f6', cat: 'Database', size: 'lg' },
  { name: 'MySQL', icon: '🗄️', color: '#f59e0b', cat: 'Database', size: 'md' },
  { name: 'MongoDB', icon: '🍃', color: '#22c55e', cat: 'Database', size: 'md' },
  { name: 'Redis', icon: '🔴', color: '#ef4444', cat: 'Cache', size: 'md' },
  { name: 'Celery', icon: '🌿', color: '#22c55e', cat: 'Task Queue', size: 'md' },
  { name: 'Docker', icon: '🐳', color: '#0ea5e9', cat: 'DevOps', size: 'md' },
  { name: 'NGINX', icon: '🔧', color: '#22c55e', cat: 'DevOps', size: 'sm' },
  { name: 'Linux', icon: '🐧', color: '#f59e0b', cat: 'DevOps', size: 'sm' },
  { name: 'Stripe', icon: '💳', color: '#6366f1', cat: 'Integration', size: 'md' },
  { name: 'Scrapy', icon: '🕷️', color: '#22c55e', cat: 'Scraping', size: 'sm' },
  { name: 'Selenium', icon: '🤖', color: '#94a3b8', cat: 'Scraping', size: 'sm' },
  { name: 'Pandas', icon: '🐼', color: '#3b82f6', cat: 'Data', size: 'sm' },
  { name: 'OpenCV', icon: '👁️', color: '#ef4444', cat: 'AI/CV', size: 'sm' },
  { name: 'Git', icon: '📦', color: '#f97316', cat: 'Tools', size: 'sm' },
  { name: 'Postman', icon: '🚀', color: '#f97316', cat: 'Tools', size: 'sm' },
];
